<#
.SYNOPSIS
Imports a TLS/SSL certificate from win-acme (simple-acme) renewal into FortiGate and configures it for HTTPS administrative management.

.DESCRIPTION
Note that this script is intended to be run via the install script plugin from win-acme. As such, we use positional parameters to avoid parsing issues with dashes in the command line within win-acme.

The script utilizes the FortiOS REST API to securely upload the PKCS#12 (PFX) file, automatically generates a unique name based on the current date (LE-yyyyMMdd) to prevent collision with active certificates, and immediately updates the global admin server certificate.

.PARAMETER PfxPath
The absolute path to the pfx file generated by win-acme. Typically use '{CacheFile}'

.PARAMETER CertPass
The password for the pfx file. Typically use '{CachePassword}'

.PARAMETER FgtIP
The IP address or FQDN of the target FortiGate unit. Optionally with ":<port>".

.PARAMETER ApiToken
The REST API token generated on FortiGate (via 'config system api-user') with 'rwrite' permissions for 'Vpn' and 'System'.

.EXAMPLE
Import-FortiGateCert.ps1 "{CacheFile}" "{CachePassword}" "192.168.1.99" "your_api_token_here"

.NOTES
To avoid 'certificate in use' deployment errors, the script dynamically names each import using the current date. Old certificates are kept on the device and must be purged manually or via a separate lifecycle script once they expire.
#>

param(
    [Parameter(Position=0,Mandatory=$true)][string]$PfxPath,
    [Parameter(Position=1,Mandatory=$true)][string]$CertPass,
    [Parameter(Position=2,Mandatory=$true)][string]$FgtIP,
    [Parameter(Position=3,Mandatory=$true)][string]$ApiToken
)

# Bypass SSL certificate validation for internal FortiGate management
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }

# Generate a unique certificate name based on the current date (e.g., LE-20260702)
$CertName = "LE-$(Get-Date -Format 'yyyyMMdd')"

# Prepare HTTP headers with the API token using the mandatory Bearer schema
$Headers = @{
    "Authorization" = "Bearer $ApiToken"
}

# 1. Validate and read the PFX file
if (-not (Test-Path $PfxPath)) {
    Write-Error "PFX file not found at path: $PfxPath"
    exit 1
}
$PfxBytes = [System.IO.File]::ReadAllBytes($PfxPath)
$Base64Pfx = [System.Convert]::ToBase64String($PfxBytes)

# 2. Import PFX into FortiGate via REST API
$ImportUrl = "https://$FgtIP/api/v2/monitor/vpn-certificate/local/import"
$ImportBody = @{
    type         = "pkcs12"
    certname     = $CertName
    file_content = $Base64Pfx
    password     = $CertPass
} | ConvertTo-Json

try {
    $Response = Invoke-RestMethod -Uri $ImportUrl -Method Post -Body $ImportBody -ContentType "application/json" -Headers $Headers -ErrorAction Stop
    if ($Response.status -eq "success") {
        Write-Host "Success: Certificate '$CertName' has been imported."
    } else {
        Write-Error "FortiGate returned an error during import: $($Response | ConvertTo-Json)"
        exit 1
    }
} catch {
    Write-Error "API call for import failed: $_"
    if ($_.Exception.Response) {
        $Reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
        Write-Error "FortiGate details: $($Reader.ReadToEnd())"
    }
    exit 1
}

# 3. Immediate activation for HTTPS Management (system global)
$ConfigUrl = "https://$FgtIP/api/v2/cmdb/system/global"
$ConfigBody = @{
    "admin-server-cert" = $CertName
} | ConvertTo-Json

try {
    $ConfigResponse = Invoke-RestMethod -Uri $ConfigUrl -Method Put -Body $ConfigBody -ContentType "application/json" -Headers $Headers -ErrorAction Stop
    if ($ConfigResponse.status -eq "success") {
        Write-Host "Success: HTTPS management is now using certificate '$CertName'."
    } else {
        Write-Error "FortiGate returned an error during configuration: $($ConfigResponse | ConvertTo-Json)"
        exit 1
    }
} catch {
    Write-Error "API call for HTTPS certificate configuration failed: $_"
    exit 1
}